# Generated by Django 2.1.7 on 2020-08-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0002_auto_20200802_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, max_length=9500, null=True, verbose_name='العنوان'),
        ),
    ]
