# Generated by Django 2.1.7 on 2020-08-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0004_remove_articles_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images', verbose_name='صورة مناسبة'),
        ),
    ]
